backend:
  name: git-gateway
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
publish_mode: editorial_workflow
local_backend: true
collections:
  - name: 'artist'
    label: 'Artysta'
    folder: 'cms/artists'
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Imię i nazwisko', name: 'name', widget: 'string' }
      - { label: 'Opis', name: 'body', widget: 'markdown' }
      - { label: 'Zdjęcie profilowe', name: 'avatar', widget: 'image' }
      - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
      - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }
      - { label: 'Behance', name: 'behance', widget: 'string', required: false }
      - { label: 'WWW', name: 'web', widget: 'string', required: false }
      - {
          label: 'Prace',
          name: 'images',
          widget: 'list',
          field: { label: 'Zdjęcie', name: 'image', widget: 'image' },
        }
  - name: 'bid'
    label: 'Licytacja'
    folder: 'cms/bids'
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Nazwa', name: 'title', widget: 'string' }
      - {
          label: 'Artysta',
          name: 'artist',
          widget: 'relation',
          collection: 'artist',
          searchFields: ['name'],
          valueField: 'name',
          displayFields: ['name'],
        }
      - {
          label: 'Typ',
          name: 'type',
          widget: 'select',
          options: ['Malarstwo', 'Ceramika', 'Plakat', 'Tkactwo'],
        }
      - { label: 'Link do licytacji', name: 'url', widget: 'string' }
      - { label: 'Format', name: 'format', widget: 'string' }
      - { label: 'Wyróżnione', name: 'featured', widget: 'boolean' }
      - {
          label: 'Zdjęcia',
          name: 'images',
          widget: 'list',
          field: { label: 'Zdjęcie', name: 'image', widget: 'image' },
        }
