backend:
  name: git-gateway
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
publish_mode: editorial_workflow
local_backend: true
collections:
  # EXAMPLE COLLECTION, WILL BE REMOVED SOON
  - name: 'artist' # Used in routes, e.g., /admin/collections/blog
    label: 'Artysta' # Used in the UI
    folder: 'cms/artists' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{name}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Imię i nazwisko', name: 'name', widget: 'string' }
      - { label: 'Opis', name: 'body', widget: 'markdown' }
      - { label: 'Zdjęcie profilowe', name: 'avatar', widget: 'image' }
      - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
      - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }
      - { label: 'Behance', name: 'behance', widget: 'string', required: false }
      - { label: 'WWW', name: 'web', widget: 'string', required: false }
      - {
          label: 'Prace',
          name: 'images',
          widget: 'list',
          field: { label: 'Zdjęcie', name: 'image', widget: 'image' },
        }
