backend:
  name: git-gateway
  branch: main
local_backend: true
media_folder: 'cms/images'
public_folder: '../images'
collections:
  - name: 'artist'
    label: 'Artysta'
    folder: 'cms/artists'
    create: true
    slug: '{{name}}'
    fields:
      - { label: 'Imię i nazwisko', name: 'name', widget: 'string' }
      - { label: 'Opis', name: 'body', widget: 'markdown' }
      - { label: 'Zdjęcie profilowe', name: 'avatar', widget: 'image' }
      - { label: 'Wyróżniony', name: 'featured', widget: 'boolean' }
      - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
      - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }
      - { label: 'Behance', name: 'behance', widget: 'string', required: false }
      - { label: 'WWW', name: 'web', widget: 'string', required: false }
      - label: 'Prace'
        name: 'images'
        widget: 'list'
        fields:
          - { label: 'Zdjęcie', name: 'image', widget: 'image' }
  - name: 'bid'
    label: 'Licytacja'
    folder: 'cms/bids'
    create: true
    slug: '{{artist}}-{{title}}'
    fields:
      - { label: 'Nazwa', name: 'title', widget: 'string' }
      - {
          label: 'Artysta',
          name: 'artist',
          widget: 'relation',
          collection: 'artist',
          searchFields: ['name'],
          valueField: 'name',
          displayFields: ['name'],
        }
      - { label: 'Zdjęcie', name: 'image', widget: 'image' }  
      - { label: 'Technika', name: 'type', widget: 'string' }
      - { label: 'Link do licytacji', name: 'url', widget: 'string', required: false }
      - { label: 'Format', name: 'format', widget: 'string' }
      - { label: 'Wyróżnione', name: 'featured', widget: 'boolean' }
